local builtin = require("telescope.builtin")
local utils = require("thib.telescope.utils")

local opts = { noremap = true, silent = true }

vim.keymap.set('n', '<leader>qf', builtin.quickfix, opts)
vim.keymap.set('n', '<leader>ff', builtin.find_files, opts)
vim.keymap.set('n', '<leader>fgg', builtin.live_grep, opts)
vim.keymap.set('n', '<leader>fb', builtin.buffers, opts)
vim.keymap.set('n', '<leader>fh', builtin.help_tags, opts)
vim.keymap.set('n', '<leader>ui', utils.search_ui_components, opts)
vim.keymap.set('n', '<leader>fgui', utils.grep_ui_components, opts)
vim.keymap.set('n', '<leader>fe', utils.search_frontend, opts)
vim.keymap.set('n', '<leader>fgfe', utils.grep_frontend, opts)
vim.keymap.set('n', '<leader>op', utils.search_operations, opts)
vim.keymap.set('n', '<leader>fgop', utils.grep_operations, opts)
vim.keymap.set('n', '<leader>wa', utils.search_workflow_automation, opts)
vim.keymap.set('n', '<leader>fgwa', utils.grep_workflow_automation, opts)
vim.keymap.set('n', '<leader>e2e', utils.search_e2e, opts)
vim.keymap.set('n', '<leader>fgc', utils.grep_cwd, opts)
vim.keymap.set('n', '<leader>fr', ':Telescope resume<cr><esc>', opts)

vim.keymap.set('v', '<leader>g', utils.grep_current_selection, opts)
vim.keymap.set('n', '<leader>sd', utils.search_dotfiles, opts)
vim.keymap.set('n', '<leader>fgsd', utils.grep_dotfiles, opts)
vim.keymap.set('n', '<leader>/', builtin.current_buffer_fuzzy_find, opts)
vim.keymap.set('n', '<leader>ee', function() builtin.symbols { sources = { 'emoji' } } end, opts)
vim.keymap.set('n', '<leader>gb', utils.git_branches, opts)
vim.keymap.set('n', "<leader>'", builtin.marks, opts)
vim.keymap.set('n', '<leader>th', function() builtin.colorscheme({ enable_preview = true }) end, opts)
