

HISTFILE=~/.zsh_history

zsh_files_path=~/.config/zsh
source "${zsh_files_path}/antigen.zsh"
source "${zsh_files_path}/benice.zsh"
source "${zsh_files_path}/gcloud.zsh"
source "${zsh_files_path}/nvim.zsh"
source "${zsh_files_path}/ros.zsh"

# Load sv.zsh only if catkin_ws is present
if [ -d "/home/sv/catkin_ws" ]
then
    source "${zsh_files_path}/sv.zsh"
fi

setopt auto_cd

# Vi Mode
bindkey -v
bindkey -M viins 'jk' vi-cmd-mode

# Kill The Lag
export KEYTIMEOUT=20

# Mode Indicator
# Updates editor information when the keymap changes.
function zle-keymap-select() {
  zle reset-prompt
  zle -R
}

zle -N zle-keymap-select

function vi_mode_prompt_info() {
  echo "${${KEYMAP/vicmd/[% NORMAL]%}/(main|viins)/[% INSERT]%}"
}

# Auto cd and ls
function chpwd() {
  emulate -L zsh
  ls --almost-all
}

# define right prompt, regardless of whether the theme defined it
RPS1='$(vi_mode_prompt_info)'
RPS2=$RPS1


# Better searching in command mode
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward

# Beginning search with arrow keys
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search

# Enable colors
autoload colors zsh/terminfo
colors


setopt complete_aliases

# Tmux with utf8 support for nice icons
alias tmux="tmux -u"
alias vim="nvim"
alias vimbegood="docker run -it --rm brandoncc/vim-be-good:stable"

# Tired of ghostscript
alias gs='git status'

# Copy to clipboard cmd (to use with piping)   -> copy the ouput of `cmd` to clipboard with :$ cmd | copy
alias copy="xclip -sel clip"


export EDITOR='vim'

# I never write docker correctly
alias dokcer="docker"
alias dkcoer="docker"

# Issue finding tensorflow without this
export PYTHONPATH=/usr/local:$PYTHONPATH
export PYTHONPATH=$PYTHONPATH:/home/sv/catkin_ws/devel/lib/python3/dist-packages
export PYTHONPATH=$PYTHONPATH:/home/sv/catkin_ws/src/svpy:/home/sv/catkin_ws/src/backend/host/bash
export PATH=~/.npm-global/bin:$PATH

export TERM="xterm-256color"

alias luamake=/home/sv/dotfiles/scripts/nvim/lua-language-server/lua-language-server/3rd/luamake/luamake
