require("ros-nvim").setup {}
require("thib.notify")
require("thib.telescope")
require("thib.nvim-tree")
require("thib.lspconfig")
require("thib.nvim-treesitter")
require("thib.format")
-- dbg module init.lua somehow cant find the files
require("thib.dbg.dapui")
require("thib.dbg.dap-virtual-text")
require("thib.dbg.dbg-config")
require("thib.dbg.lua-dap")
require("thib.nvim-tree")
require("thib.glab")
require("thib.utils")
require("thib.refactoring")
